### ISSUE TITLE
Handle Special Characters

### ISSUE THREAD

**Issue by hbatalhaStch** [divijhardwaj/json-xml-parse#5]
The package does not encode XML special characters (" ' < > &):
It should have a function to convert these characters into their encodings:

| Character | Encoding|
|-----------|------------|
| `&`          | `&amp;`    |
| `<`          | `&lt;`         |
| `>`          | `&gt;`       |
| `"`           | `&quot;`   |
| `'`           | `&apos;`   |

**Comment by dlvlj** [comment]
Hi, I have just released v1.3.0 the issue should be fixed with this.
the previous version only had `<,>,"` entities encoded by default.
The package allows users to override the default entity set by passing the `entityMap` object in the options.

Thank you very much for contributing. 
Feel free to create a merge request.

**Comment by hbatalhaStch** [comment]
I didn't notice the entityMap, I came up with a temp fix but good to know it was already there.
I will update soon.
